### PR TITLE
Fix/post

### PR DESCRIPTION
**Pull request by NishthaLath**
The code works great and there weren't many necessary issues to be corrected but i have tried my best to make it more efficient and readable. 
- Updated Post.java, PostRepository.java, PostService.java
- No changes to PostController.java

 Thank you, Looking forward to any suggestions.

### CODE REVIEW

**Comment by Village-GG-Water** [comment]
javax.validation.constraints package가 존재하지 않는다고 하니 확인 부탁드립니다.

**Comment by LAPLACE4A** [comment]
> javax.validation.constraints package가 존재하지 않는다고 하니 확인 부탁드립니다.

https://github.com/KERT-core/KERT_Introduction_Website-BE/pull/20/commits/17cafdbee49a660847a96caf2dfccee9401b422e
deprecated된 어노테이션으로 작업하셨길래 바꿨습니다

**Comment by NishthaLath** [comment]
> > javax.validation.constraints package가 존재하지 않는다고 하니 확인 부탁드립니다.
> 
> [17cafdb](https://github.com/KERT-core/KERT_Introduction_Website-BE/commit/17cafdbee49a660847a96caf2dfccee9401b422e) deprecated된 어노테이션으로 작업하셨길래 바꿨습니다

Thank you

**Review by Village-GG-Water — APPROVED** [review]
LGTM

**Pull request merged**
